In [1]:
import torch

In [3]:
print(torch.cuda.device_count())

1


In [4]:
print(torch.cuda.current_device())

0


In [6]:
print(torch.cuda.is_available())

True


In [10]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('Using device:', device)
print()

#Additional Info when using cuda
if device.type == 'cuda':
    print(torch.cuda.get_device_name(0))
    print('Memory Usage:')
    print('Allocated:', round(torch.cuda.memory_allocated(0)/1024**3,1), 'GB')
    print('Cached:   ', round(torch.cuda.memory_reserved(0)/1024**3,1), 'GB')

Using device: cuda

NVIDIA GeForce RTX 2060
Memory Usage:
Allocated: 0.0 GB
Cached:    0.0 GB


In [11]:
cuda0 = torch.device('cuda:0')
torch.ones([2, 4], dtype=torch.float64, device=cuda0)
a = torch.cuda.IntTensor(3, 3)

In [12]:
torch.cuda.get_device_name(device=cuda0)

'NVIDIA GeForce RTX 2060'

In [13]:
torch.cuda.init()

In [14]:
 torch.cuda.is_initialized()

True

In [15]:
a = torch.randn(3, 3)
a = torch.mm(a, a.t())
l = torch.cholesky(a)
a, l

(tensor([[ 2.8211,  0.3940,  1.9741],
         [ 0.3940,  0.6479, -0.0929],
         [ 1.9741, -0.0929,  3.1343]]),
 tensor([[ 1.6796,  0.0000,  0.0000],
         [ 0.2346,  0.7700,  0.0000],
         [ 1.1754, -0.4787,  1.2344]]))

In [16]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [2]:
a = torch.ones(3, 2)

In [3]:
a.storage_offset()

0

In [4]:
a.stride()

(2, 1)

In [5]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point[0] = 10.0
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [6]:
some_t = torch.ones(3, 4, 5)
transpose_t = some_t.transpose(0, 2)
some_t.shape, transpose_t.shape

(torch.Size([3, 4, 5]), torch.Size([5, 4, 3]))

In [7]:
id(some_t.storage()) == id(transpose_t.storage())

True

In [9]:
transpose_t.is_contiguous()

False

In [10]:
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')

In [11]:
points_gpu = points.to(device='cuda')

In [12]:
points = 2 * points
points_gpu = 2 * points.to(device='cuda')